version: "3.9"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true # Không public

services:
  nginx:
    image: nginx:lastes
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./angular/dist:/usr/share/nginx/html
    depends_on:
      - springboot
    networks:
      - frontend
      - backend
  
  springboot:
    build: ./be
    container_name: springboot
    networks:
      - backend
      - frontend
    depends_on:
      - python-service

  angular:
    build: ./fe
    container_name: angular
    depends_on:
      - nginx
    networks:
      - frontend

  python-service:
    build: ./python
    container_name: python-service
    expose:
      - "8000"  # nội bộ
    networks:
      - backend


  

