version: "3.9"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true # Không public

services:
  
  python-service:
    build: ./py
    container_name: python-service
    expose:
      - "8000"  # nội bộ
    networks:
      - backend

  springboot:
    build: ./be
    container_name: springboot
    expose: 
      - "8080"
    networks:
      - backend
      - frontend
    depends_on:
      - python-service

  angular:
    build: ./fe
    container_name: angular
    ports: 
      - "80:80"
    depends_on:
      - springboot
    networks:
      - frontend
    volumes:
      - ./fe/nginx.conf:/etc/nginx/conf.d/default.conf



  

