version: "3.9"

# volumes:
#   font-base:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /root/app-test/font-base

#   font-res:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /root/app-test/res

# networks:
#   frontend:
#     driver: bridge
#   backend:
#     driver: bridge
#     internal: true # Không public

services:
  
#   python-service:
#     build: ./py
#     container_name: python-service
#     expose:
#       - "8000"  # nội bộ
#     networks:
#       - backend
#     volumes:
#       - font-base:/font-base:rw
#       - font-res:/res:rw

#   springboot:
#     build: ./be
#     container_name: springboot
#     expose: 
#       - "8080"
#     networks:
#       - backend
#       - frontend
#     depends_on:
#       - python-service

#   angular:
#     build: ./fe
#     container_name: angular
#     ports: 
#       - "80:80"
#     depends_on:
#       - springboot
#     networks:
#       - frontend
#     volumes:
#       - ./fe/nginx.conf:/etc/nginx/conf.d/default.conf

  # py2 securetex
  py2:
    build: ./py2
    container_name: py2
    ports:
      - "8001:8001"
    

  

